name: "Android ARM64 Static Build"

on:
  workflow_dispatch:

jobs:
  build-android-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Android ARM64 static binary
      run: |
        # Create Dockerfile for Android ARM64 build environment
        cat > Dockerfile.android-arm64 << 'EOF'
        FROM ubuntu:22.04

        ENV DEBIAN_FRONTEND=noninteractive
        ENV TZ=Etc/UTC

        # Install basic dependencies
        RUN apt-get update && apt-get install -y \
            build-essential \
            cmake \
            git \
            wget \
            curl \
            gnupg \
            software-properties-common \
            apt-transport-https \
            ca-certificates \
            python3 \
            bison \
            flex \
            libelf-dev \
            zlib1g-dev \
            libfl-dev \
            libcereal-dev \
            liblzma-dev \
            libiberty-dev \
            libzstd-dev \
            libncurses-dev \
            autoconf \
            libtool \
            libdwarf-dev \
            libdw-dev \
            binutils-dev \
            libxml2-dev \
            libbz2-dev \
            pkg-config \
            sed \
            libpcap-dev

        # Install LLVM 16
        RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
            echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main" >> /etc/apt/sources.list.d/llvm.list && \
            apt-get update && \
            apt-get install -y \
                llvm-16 \
                llvm-16-dev \
                clang-16 \
                libclang-16-dev \
                libllvm16 \
                libz3-dev && \
            # Check installation
            ls -la /usr/bin/llvm-config-16 && \
            /usr/bin/llvm-config-16 --version

        # Set LLVM 16 as default
        RUN update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-16 100 && \
            update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 100
            
        # Install libbpf v1.5.0
        WORKDIR /opt
        RUN git clone https://github.com/libbpf/libbpf.git && \
            cd libbpf && \
            git checkout v1.5.0 && \
            cd src && \
            make BUILD_STATIC_ONLY=y OBJDIR=/tmp/libbpf DESTDIR=/tmp/libbpf install && \
            cp -r /tmp/libbpf/usr/lib64/libbpf.a /usr/lib/ && \
            cp -r /tmp/libbpf/usr/include/* /usr/include/ && \
            ls -la /usr/lib/libbpf.a && \
            find /usr/include -name "bpf*.h" | sort && \
            cat /usr/include/bpf/libbpf_version.h

        # Get BCC (both headers and libraries)
        WORKDIR /opt
        RUN git clone https://github.com/iovisor/bcc.git -b v0.24.0 && \
            mkdir -p bcc/build && \
            cd bcc/build && \
            cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
                     -DENABLE_EXAMPLES=OFF \
                     -DENABLE_MAN=OFF \
                     -DENABLE_TESTS=OFF \
                     -DENABLE_TOOLS=OFF && \
            make -j$(nproc) && \
            make install && \
            ls -la /usr/lib/libbcc* || true && \
            ls -la /usr/include/bcc || true

        WORKDIR /bpftrace
        EOF

        # Build Docker image with platform set to arm64 and load it into Docker
        docker buildx build --platform linux/arm64 --load -t bpftrace-android-arm64 -f Dockerfile.android-arm64 .

        # Create build script
        cat > build-android-arm64.sh << 'EOF'
        #!/bin/bash
        set -ex

        # Display environment information
        echo "===== Environment Information ====="
        echo "LLVM version:"
        llvm-config --version
        echo "Include header directories:"
        ls -la /usr/include/bcc/
        ls -la /usr/include/bpf/
        echo "libbpf library:"
        find /usr -name libbpf.a
        echo "libbcc library:"
        find /usr -name "libbcc*.a" || true
        find /usr -name "libbcc*.so" || true
        echo "libbpf version:"
        cat /usr/include/bpf/libbpf_version.h
        echo "Architecture:"
        uname -m

        # Create patched source directory
        echo "Creating patched source directory..."
        mkdir -p /bpftrace-patched
        cp -r /bpftrace/* /bpftrace-patched/
        cd /bpftrace-patched

        # Patch src/CMakeLists.txt to fix zstd references
        echo "Patching src/CMakeLists.txt for zstd..."
        grep -r "zstd::libzstd_shared" src || true
        
        # Replace zstd::libzstd_shared with ZLIB::ZLIB
        if grep -q "zstd::libzstd_shared" src/CMakeLists.txt; then
            sed -i 's/zstd::libzstd_shared/ZLIB::ZLIB/g' src/CMakeLists.txt
        fi
        
        if grep -q "zstd::libzstd_shared" src/ast/CMakeLists.txt; then
            sed -i 's/zstd::libzstd_shared/ZLIB::ZLIB/g' src/ast/CMakeLists.txt
        fi
        
        # Add more comprehensive modifications to handle libbcc library paths
        if grep -q "find_package(LibBcc REQUIRED)" CMakeLists.txt; then
            echo "Modifying CMakeLists.txt for BCC libraries"
            cat > patch.txt << 'EOL'
        --- a/CMakeLists.txt
        +++ b/CMakeLists.txt
        @@ -80,7 +80,16 @@
         find_package(LibElf REQUIRED)
         find_package(ZLIB REQUIRED)
         
        -find_package(LibBcc REQUIRED)
        +find_package(LibBcc)
        +
        +# Handle case when BCC is not found
        +if(NOT LIBBCC_FOUND)
        +  message(STATUS "Setting manual BCC variables")
        +  set(LIBBCC_LIBRARIES "/usr/lib/libbcc.a")
        +  set(LIBBCC_BPF_LIBRARIES "/usr/lib/libbcc_bpf.a")
        +  set(LIBBCC_LOADER_LIBRARY_STATIC "/usr/lib/libbcc.a")
        +  set(LIBBCC_INCLUDE_DIRS "/usr/include")
        +endif()
        +
         find_package(LibBpf)
         
         option(HAVE_BFD_DISASM "Use libbfd disassembler instead of LLVM" OFF)
        EOL
            patch -p1 < patch.txt || true
        fi
        
        # Skip libbpf version check
        if grep -q "bpftrace requires libbpf" CMakeLists.txt; then
            echo "Removing libbpf version check"
            sed -i 's/if(LIBBPF_FOUND AND LIBBPF_VERSION VERSION_LESS.*)/if(FALSE)/' CMakeLists.txt
        fi

        echo "Building static bpftrace..."
        mkdir -p build-android
        cd build-android

        # Configure with CMake - disable features that may cause issues
        LLVM_REQUESTED_VERSION=16 cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DBUILD_TESTING=OFF \
          -DSTATIC_LINKING=ON \
          -DALLOW_UNSAFE_PROBE=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DENABLE_MAN=OFF \
          -DENABLE_LIBBLAZESYM=OFF \
          -DCMAKE_SKIP_BUILD_RPATH=ON \
          -DSKIP_BCC_DIRECT_EXPORT=ON \
          -DHAVE_BCC_PROG_LOAD=OFF \
          -DHAVE_BCC_CREATE_MAP=OFF

        # Check cmake configurations
        echo "CMake configuration summary:"
        grep -r "LIBBCC_" CMakeCache.txt || true
        grep -r "STATIC_LINKING" CMakeCache.txt || true
        
        # Build - first try with multiple cores, fallback to single thread if issues
        make -j$(nproc) VERBOSE=1 || make VERBOSE=1

        # Check for the binary
        if [ -f "src/bpftrace" ]; then
          echo "Build successful!"
          file src/bpftrace
          
          # Create release package
          mkdir -p release/android-arm64
          cp src/bpftrace release/android-arm64/
          
          # Copy tools if available
          if [ -d "../tools" ]; then
            cp -r ../tools release/android-arm64/
            chmod +x release/android-arm64/tools/*.bt 2>/dev/null || true
          fi
          
          tar -czf /bpftrace/bpftrace-android-arm64-static.tar.gz -C release android-arm64
          echo "Package created: bpftrace-android-arm64-static.tar.gz"
        else
          echo "Build failed - bpftrace binary not found!"
          echo "==== Build Error Information ===="
          find . -name "*.log" | xargs cat || true
          exit 1
        fi
        EOF

        chmod +x build-android-arm64.sh

        # Run build in Docker with platform set to arm64
        docker run --platform linux/arm64 --rm -v $(pwd):/bpftrace -w /bpftrace bpftrace-android-arm64 ./build-android-arm64.sh || true

        # Check if the tar.gz file was created
        if [ -f "bpftrace-android-arm64-static.tar.gz" ]; then
          echo "Build package created successfully."
        else
          echo "Build failed - package not created."
          exit 1
        fi

    - name: Upload Android ARM64 static binary artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bpftrace-android-arm64-build-logs
        path: |
          build*
          bpftrace-android-arm64-static.tar.gz
          
    - name: Create Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        name: Android ARM64 Static Build
        tag_name: android-arm64-static-${{ github.run_number }}
        files: bpftrace-android-arm64-static.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
