name: "Android ARM64 Static Build"

on:
  workflow_dispatch:

jobs:
  build-android-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Android ARM64 static binary
      run: |
        # 创建Dockerfile - 使用新的简化方法直接构建bpftrace
        cat > Dockerfile.android-arm64 << 'EOF'
        FROM ubuntu:22.04

        ENV DEBIAN_FRONTEND=noninteractive
        ENV TZ=Etc/UTC

        # 安装基本依赖
        RUN apt-get update && apt-get install -y \
            build-essential \
            cmake \
            git \
            wget \
            curl \
            gnupg \
            software-properties-common \
            python3 \
            bison \
            flex \
            libelf-dev \
            zlib1g-dev \
            libfl-dev \
            libcereal-dev \
            liblzma-dev \
            libiberty-dev \
            libzstd-dev \
            libncurses-dev \
            autoconf \
            libtool \
            binutils-aarch64-linux-gnu \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libdwarf-dev \
            libdw-dev \
            binutils-dev \
            libxml2-dev

        # 安装LLVM 16
        RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
            echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main" >> /etc/apt/sources.list && \
            apt-get update && \
            apt-get install -y \
                llvm-16 \
                llvm-16-dev \
                clang-16 \
                libclang-16-dev \
                libllvm16 \
                libz3-dev

        # 设置LLVM 16为默认版本
        RUN update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-16 100 && \
            update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 100
            
        # 创建ARM64交叉编译工具链目录
        RUN mkdir -p /usr/aarch64-linux-gnu/include /usr/aarch64-linux-gnu/lib
        
        # 从预编译的二进制文件下载BPF和BCC
        WORKDIR /opt
        
        # 下载并安装预编译的libbpf
        RUN curl -L -o libbpf.tar.gz https://github.com/libbpf/libbpf/archive/refs/tags/v1.2.0.tar.gz && \
            tar xf libbpf.tar.gz && \
            cd libbpf-* && \
            cd src && \
            make BUILD_STATIC_ONLY=y OBJDIR=/tmp/libbpf DESTDIR=/tmp/libbpf install && \
            cp -r /tmp/libbpf/usr/lib64/libbpf.a /usr/lib/ && \
            cp -r /tmp/libbpf/usr/include/* /usr/include/ && \
            cp -r /tmp/libbpf/usr/lib64/libbpf.a /usr/aarch64-linux-gnu/lib/ && \
            cp -r /tmp/libbpf/usr/include/* /usr/aarch64-linux-gnu/include/
            
        # 创建静态构建目录
        WORKDIR /src

        # 克隆bcc但只安装头文件，不构建库
        RUN git clone https://github.com/iovisor/bcc.git -b v0.24.0 && \
            mkdir -p /usr/include/bcc /usr/aarch64-linux-gnu/include/bcc && \
            cp -r /src/bcc/src/cc/api/* /usr/include/bcc/ && \
            cp -r /src/bcc/src/cc/libbpf.h /usr/include/bcc/ && \
            cp -r /src/bcc/src/cc/bpf_common.h /usr/include/bcc/ && \
            cp -r /src/bcc/src/cc/api/* /usr/aarch64-linux-gnu/include/bcc/ && \
            cp -r /src/bcc/src/cc/libbpf.h /usr/aarch64-linux-gnu/include/bcc/ && \
            cp -r /src/bcc/src/cc/bpf_common.h /usr/aarch64-linux-gnu/include/bcc/

        # 在这个方法中，我们只使用bpftrace的libbpf后端，不需要bcc的完整构建

        WORKDIR /bpftrace
        EOF

        # 构建Docker镜像
        docker build -t bpftrace-android-arm64 -f Dockerfile.android-arm64 .

        # 创建构建脚本
        cat > build-android-arm64.sh << 'EOF'
        #!/bin/bash
        set -ex

        # 显示环境信息
        echo "===== 环境信息 ====="
        echo "LLVM版本:"
        llvm-config --version
        echo "包含头文件目录:"
        ls -la /usr/include/bcc/
        ls -la /usr/include/bpf/
        echo "libbpf库:"
        find /usr -name "libbpf.a"

        # 创建交叉编译工具链文件
        cat > arm64_toolchain.cmake << 'CMAKEEOF'
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_SYSTEM_PROCESSOR aarch64)

        set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
        set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

        set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
        set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

        # 库文件
        set(ZLIB_LIBRARY /usr/lib/x86_64-linux-gnu/libz.a)
        set(ZLIB_INCLUDE_DIR /usr/include)
        
        set(LIBELF_LIBRARIES /usr/lib/x86_64-linux-gnu/libelf.a)
        set(LIBELF_INCLUDE_DIRS /usr/include)
        
        set(LIBLZMA_LIBRARIES /usr/lib/x86_64-linux-gnu/liblzma.a)
        set(LIBLZMA_INCLUDE_DIRS /usr/include)
        
        # LIBBPF设置
        set(LIBBPF_LIBRARIES /usr/lib/libbpf.a)
        set(LIBBPF_INCLUDE_DIRS /usr/include)
        
        # BCC头文件目录，但我们不实际链接BCC库
        set(LIBBCC_INCLUDE_DIRS /usr/include)
        CMAKEEOF
        
        # 创建构建目录
        mkdir -p build-android-arm64
        cd build-android-arm64
        
        # 配置bpftrace构建 - 直接使用LIBBPF后端，不使用BCC
        LLVM_REQUESTED_VERSION=16 cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=../arm64_toolchain.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_STANDARD=17 \
          -DBUILD_TESTING=OFF \
          -DENABLE_MAN=OFF \
          -DENABLE_LIBDW=OFF \
          -DENABLE_LLVM_JIT=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -DUSE_LIBCC_POINTER_LOOKUP=OFF \
          -DUSE_LIBBFD=OFF \
          -DALLOW_UNNECESSARY_LIBBPF=ON \
          -DENABLE_BPF_MSGTYPES=OFF
          
        # 构建
        make -j$(nproc) VERBOSE=1 || true
        
        # 检查是否有bpftrace可执行文件
        if [ -f "src/bpftrace" ]; then
          echo "构建成功!"
          file "src/bpftrace"
          
          # 创建发布包
          mkdir -p release/android-arm64
          cp "src/bpftrace" release/android-arm64/
          cp -r /bpftrace/tools release/android-arm64/ || true
          chmod +x release/android-arm64/tools/*.bt 2>/dev/null || true
          tar -czf /bpftrace/bpftrace-android-arm64-static.tar.gz -C release android-arm64
        else
          echo "构建失败 - 找不到bpftrace二进制文件!"
          
          # 显示CMake日志以帮助调试
          echo "==== CMake错误日志 ===="
          cat CMakeFiles/CMakeError.log || true
          echo "==== CMake输出日志 ===="
          cat CMakeFiles/CMakeOutput.log || true
          
          # 额外调试信息
          echo "===== 目录结构 ====="
          find . -type f -name "*.a" | sort
          echo "===== 编译错误信息 ====="
          find . -name "*.log" | xargs cat
          
          exit 1
        fi
        EOF

        chmod +x build-android-arm64.sh

        # 在Docker中运行交叉编译
        docker run --rm -v $(pwd):/bpftrace -w /bpftrace bpftrace-android-arm64 ./build-android-arm64.sh || true

        # 检查是否生成了tar.gz文件
        if [ -f "bpftrace-android-arm64-static.tar.gz" ]; then
          echo "构建包创建成功。"
        else
          echo "构建失败 - 未创建包。"
          exit 1
        fi

    - name: Upload Android ARM64 static binary
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bpftrace-android-arm64-build-logs
        path: |
          build*
          bpftrace-android-arm64-static.tar.gz
          
    - name: Create Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        name: Android ARM64 Static Build
        tag_name: android-arm64-static-${{ github.run_number }}
        files: bpftrace-android-arm64-static.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
